In [1]:
import os
import sys

import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo 
from sklearn.preprocessing import LabelEncoder

In [ ]:
# german
german = fetch_ucirepo(id=144) 
  
X = german.data.features 
y = german.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])
    
# Change the name of the target column
y.columns = ["Class"]
y["Class"] = y["Class"] - 1

# Merge both into a single dataframe
data = pd.concat([X, y], axis=1)

data.to_csv("data/german.csv", index=False)

/tmp/ipykernel_155937/4291663075.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Class"] = y["Class"] - 1

In [4]:
# adult
adult = fetch_ucirepo(id=2) 
  
# data (as pandas dataframes) 
X = adult.data.features 
y = adult.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])
    
    
# Change the name of the target column
y.columns = ["Class"]
y['Class'] = y['Class'].str.strip().str.rstrip('.')
y["Class"] = le.fit_transform(y["Class"])

# Merge both into a single dataframe
data = pd.concat([X, y], axis=1)

data.to_csv("data/adult.csv", index=False)

/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_155937/691529708.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Class'] = y['Class'].str.strip().str.rstrip('.')
/tmp/ipykernel_155937/691529708.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Class"] = le.fit_transform(y["Class"])

In [5]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/bank8FM.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/bank8FM.csv", index=False)

FileNotFoundError: [Errno 2] No such file or directory: 'data/bank8FM.arff'

In [18]:
df["binaryClass"].value_counts()

binaryClass
1    4885
0    3307
Name: count, dtype: int64

In [3]:
# kr-vs-kp
krkp = fetch_ucirepo(id=22) 
  
# data (as pandas dataframes) 
X = krkp.data.features 
y = krkp.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])
    
    
# Change the name of the target column
y.columns = ["Class"]
y['Class'] = y['Class'].str.strip().str.rstrip('.')
y["Class"] = le.fit_transform(y["Class"])

# Merge both into a single dataframe
data = pd.concat([X, y], axis=1)

data.to_csv("data/krkp.csv", index=False)

/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/772614627.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['Class'] = y['Class'].str.strip().str.rstrip('.')
/tmp/ipykernel_3809755/772614627.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Class"] = le.fit_transform(y["Class"])

In [29]:
data = pd.read_csv("data/phishing.csv")
data["Class"].value_counts(normalize=True)

Class
1    0.556943
0    0.443057
Name: proportion, dtype: float64

In [20]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/php8Mz7BG.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["Class"] = LabelEncoder().fit_transform(df["Class"])

# Save as CSV
df.to_csv("data/phoneme.csv", index=False)

In [24]:
# phishing
phishing = fetch_ucirepo(id=327) 

# data (as pandas dataframes)
X = phishing.data.features
y = phishing.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])

In [28]:
# phishing
phishing = fetch_ucirepo(id=327) 

# data (as pandas dataframes)
X = phishing.data.features
y = phishing.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])
    
    
# Change the name of the target column
y.columns = ["result"]
y["result"] = le.fit_transform(y["result"])

# Merge both into a single dataframe
data = pd.concat([X, y], axis=1)

data.to_csv("data/phishing.csv", index=False)

/tmp/ipykernel_3809755/417629595.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["result"] = le.fit_transform(y["result"])

In [30]:
# phishing
phishing = fetch_ucirepo(id=27) 

# data (as pandas dataframes)
X = phishing.data.features
y = phishing.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])

/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/1041070004.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])

In [32]:
# phishing
credit = fetch_ucirepo(id=27) 

# data (as pandas dataframes)
X = credit.data.features
y = credit.data.targets

# Encode using label encoding
le = LabelEncoder()
for col in X.select_dtypes(include=['object']).columns:
    X[col] = le.fit_transform(X[col])
    
    
# Change the name of the target column
y.columns = ["A16"]
y["A16"] = le.fit_transform(y["A16"])

# Merge both into a single dataframe
data = pd.concat([X, y], axis=1)

data.to_csv("data/credit.csv", index=False)

/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X[col] = le.fit_transform(X[col])
/tmp/ipykernel_3809755/2483602553.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["A16"] = le.fit_transform(y["A16"])

In [4]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/puma8NH.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)

In [6]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/puma8NH.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/puma8NH.csv", index=False)

In [9]:
df["binaryClass"].value_counts(normalize=True)

binaryClass
1    0.502197
0    0.497803
Name: proportion, dtype: float64

In [1]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/pc4.arff")

In [7]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/pc4.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["c"] = LabelEncoder().fit_transform(df["c"])

# Save as CSV
df.to_csv("data/pc4.csv", index=False)

In [9]:
df["c"].value_counts(normalize=True)

c
0    0.877915
1    0.122085
Name: proportion, dtype: float64

In [ ]:
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/delta_elevators.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/deltae.csv", index=False)

KeyError: 'binaryClass'

In [6]:
df["binaryClass"].value_counts(normalize=True)

binaryClass
0    0.502784
1    0.497216
Name: proportion, dtype: float64

In [8]:
# Elevators
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/delta_elevators.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/elevators.csv", index=False)

In [22]:
# raising
raising = fetch_ucirepo(id=850) 

# data (as pandas dataframes)
X = raising.data.features
y = raising.data.targets

# Encode using label encoding
le = LabelEncoder()

y["Class"] = le.fit_transform(y["Class"])

data = pd.concat([X, y], axis=1)

data.to_csv("data/raising.csv", index=False)

/tmp/ipykernel_1843636/3121387934.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Class"] = le.fit_transform(y["Class"])

In [25]:
data.shape

(900, 8)

In [23]:
data["Class"].value_counts(normalize=True)

Class
1    0.5
0    0.5
Name: proportion, dtype: float64

In [18]:
# liver
liver = fetch_ucirepo(id=225) 

# data (as pandas dataframes)
X = liver.data.features
y = liver.data.targets

# Encode using label encoding
le = LabelEncoder()

X["Gender"] = le.fit_transform(X["Gender"])
y["Selector"] = le.fit_transform(y["Selector"])

data = pd.concat([X, y], axis=1)

data.to_csv("data/liver.csv", index=False)

/tmp/ipykernel_1843636/2868934574.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Gender"] = le.fit_transform(X["Gender"])
/tmp/ipykernel_1843636/2868934574.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["Selector"] = le.fit_transform(y["Selector"])

In [19]:
data.shape

(583, 11)

In [21]:
data["Selector"].value_counts(normalize=True)

Selector
0    0.713551
1    0.286449
Name: proportion, dtype: float64

In [15]:
# magic
magic = fetch_ucirepo(id=159) 

# data (as pandas dataframes)
X = magic.data.features
y = magic.data.targets

# Encode using label encoding
le = LabelEncoder()

y["class"] = le.fit_transform(y["class"])
data = pd.concat([X, y], axis=1)

data.to_csv("data/magic.csv", index=False)

/tmp/ipykernel_1843636/934180261.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["class"] = le.fit_transform(y["class"])

In [17]:
data.shape

(19020, 11)

In [16]:
data["class"].value_counts(normalize=True)

class
0    0.64837
1    0.35163
Name: proportion, dtype: float64

In [11]:
# vertebral
vertebral = fetch_ucirepo(id=212) 

# data (as pandas dataframes)
X = vertebral.data.features
y = vertebral.data.targets

# Encode using label encoding
le = LabelEncoder()

y["class"] = le.fit_transform(y["class"])

# 2 in target to 0
y["class"] = y["class"].replace(2, 0)
data = pd.concat([X, y], axis=1)

data.to_csv("data/vertebral.csv", index=False)

/tmp/ipykernel_1843636/1504234404.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["class"] = le.fit_transform(y["class"])
/tmp/ipykernel_1843636/1504234404.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y["class"] = y["class"].replace(2, 0)

In [14]:
data.shape

(310, 7)

In [13]:
data["class"].value_counts(normalize=True)

class
0    0.677419
1    0.322581
Name: proportion, dtype: float64

In [8]:
# QSAR
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/phpGUrE90.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["Class"] = LabelEncoder().fit_transform(df["Class"])

# Save as CSV
df.to_csv("data/qsar.csv", index=False)

In [10]:
df.shape

(1055, 42)

In [9]:
df["Class"].value_counts(normalize=True)

Class
0    0.662559
1    0.337441
Name: proportion, dtype: float64

In [5]:
# EEG
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/phplE7q6h.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["Class"] = LabelEncoder().fit_transform(df["Class"])

# Save as CSV
df.to_csv("data/eeg.csv", index=False)

In [7]:
df["Class"].value_counts(normalize=True)

Class
0    0.551202
1    0.448798
Name: proportion, dtype: float64

In [3]:
# CPU
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/cpu_small.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/cpu.csv", index=False)

In [4]:
df["binaryClass"].value_counts(normalize=True)

binaryClass
0    0.697632
1    0.302368
Name: proportion, dtype: float64

In [30]:
# banknote
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/php50jXam.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
display(df)
df["Class"] = LabelEncoder().fit_transform(df["Class"])

# Save as CSV
df.to_csv("data/banknote.csv", index=False)

           V1        V2       V3       V4 Class
0     3.62160   8.66610  -2.8073 -0.44699  b'1'
1     4.54590   8.16740  -2.4586 -1.46210  b'1'
2     3.86600  -2.63830   1.9242  0.10645  b'1'
3     3.45660   9.52280  -4.0112 -3.59440  b'1'
4     0.32924  -4.45520   4.5718 -0.98880  b'1'
...       ...       ...      ...      ...   ...
1367  0.40614   1.34920  -1.4501 -0.55949  b'2'
1368 -1.38870  -4.87730   6.4774  0.34179  b'2'
1369 -3.75030 -13.45860  17.5932 -2.77710  b'2'
1370 -3.56370  -8.38270  12.3930 -1.28230  b'2'
1371 -2.54190  -0.65804   2.6842  1.19520  b'2'

[1372 rows x 5 columns]

In [ ]:
# ailerons
import pandas as pd
from scipy.io import arff

# Load ARFF file
data, meta = arff.loadarff("data/ailerons.arff")

# Convert to pandas DataFrame
df = pd.DataFrame(data)
df["binaryClass"] = LabelEncoder().fit_transform(df["binaryClass"])

# Save as CSV
df.to_csv("data/ailerons.csv", index=False)

,climbRate,Sgz,p,q,curPitch,curRoll,absRoll,diffClb,diffRollRate,diffDiffClb,...,diffSeTime8,diffSeTime9,diffSeTime10,diffSeTime11,diffSeTime12,diffSeTime13,diffSeTime14,alpha,Se,binaryClass
0,2.0,-56.0,-0.33,-0.09,0.90,0.2,-11.0,12.0,0.004,-0.1,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.032,b'P'
1,470.0,-39.0,0.02,0.12,0.39,-0.6,-12.0,8.0,0.009,-1.6,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.034,b'P'
2,165.0,4.0,0.14,0.14,0.78,0.4,-11.0,-9.0,-0.003,-0.2,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,1.0,0.034,b'P'
3,-113.0,5.0,-0.12,0.11,1.06,0.6,-10.0,-7.0,-0.008,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.9,0.033,b'P'
4,-411.0,-21.0,-0.17,0.07,1.33,-0.6,-11.0,0.0,0.002,0.1,...,0.0,0.0,0.0,0.0,0.0,-0.002,0.0,0.9,0.032,b'N'
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13745,399.0,-22.0,0.17,0.20,0.36,-0.2,-9.0,-3.0,0.010,-3.9,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.8,0.027,b'N'
13746,237.0,-6.0,0.26,0.10,0.52,0.7,-8.0,-8.0,-0.004,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.8,0.027,b'P'
13747,-148.0,-3.0,-0.37,0.09,0.89,0.7,-8.0,-7.0,-0.013,-0.2,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.7,0.026,b'N'
13748,-237.0,-11.0,-0.47,-0.16,0.90,-0.4,-9.0,8.0,0.010,2.8,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.7,0.023,b'N'
13749,128.0,-14.0,-0.07,-0.11,0.50,-1.2,-10.0,15.0,0.017,-0.5,...,0.0,0.0,0.0,0.0,0.0,0.000,0.0,0.6,0.022,b'N'

In [33]:
df["binaryClass"].value_counts(normalize=True)

binaryClass
0    0.576145
1    0.423855
Name: proportion, dtype: float64